#!/bin/bash
:'
This script checks if the selenium process is currently running 1) if no : run selenium, 2) if yes : kill current process and run selenium in background
It also checks if story book is currently running 1) if no : run storybook, 2) if yes : print the message that storybook is already running
'
exitstatus=`ps -ef | grep "selenium"|grep -v grep | awk '{ print $2}'`
echo "selenium process id" $exitstatus
if [ "$exitstatus" = "" ]; then
        yarn selenium install --version=3.4.0
	( yarn selenium start --version=3.4.0 2>&1 | tee -a output/selenium_log.txt ) &
else
	kill -9 $exitstatus
	yarn selenium install --version=3.4.0
        ( yarn selenium start --version=3.4.0 2>&1 | tee -a output/selenium_log.txt ) &

fi

# @NB: using selenium version 3.4.0 as per: https://github.com/Codeception/CodeceptJS/issues/687

sbstatus=`ps -ef | grep "storybook"|grep -v grep | awk '{ print $2}'`
echo "storybook process id" $sbstatus
if [ "$sbstatus" = "" ]; then
    yarn storybook:watch
else
	echo "storybook process is already running"
fi
